@api =  http://127.0.0.1:3800/api/v1


### Unprotected endpoint
GET {{api}}/health
Content-Type: application/json

### Protected endpoint
GET {{api}}/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Nzc2ODcwMjYsImlhdCI6MTY3NzY4NjcyNiwic3ViIjoiam9obiJ9.jBfhXYFGNJd2SU5m69xSc7g1SHkMIFkWX8b6AH1ERzQ

### Register an user
POST {{api}}/register
Content-Type: application/json

{
    "username": "john",
    "password": "testing"
}

### Login
POST {{api}}/login
Content-Type: application/json

{
    "username": "marles",
    "password": "marles"
}


### Notes
POST {{api}}/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTI5MjE3MDMsImlhdCI6MTY5MjkyMTQwMywic3ViIjoibWFybGVzIn0.xElqscEAJjE5EO1fQw28hO5BF4-G9_y1aUD_iFtqtoU

{
    "text": "marles note 4",
    "completed": false
}



### Protected endpoint
GET {{api}}/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTI5MjE3MDMsImlhdCI6MTY5MjkyMTQwMywic3ViIjoibWFybGVzIn0.xElqscEAJjE5EO1fQw28hO5BF4-G9_y1aUD_iFtqtoU
